# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gmilliez/work/toaster-lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gmilliez/work/toaster-lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gmilliez/work/toaster-lib/CMakeFiles /home/gmilliez/work/toaster-lib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gmilliez/work/toaster-lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named toaster

# Build rule for target.
toaster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 toaster
.PHONY : toaster

# fast build rule for target.
toaster/fast:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/build
.PHONY : toaster/fast

src/Agent.o: src/Agent.cpp.o
.PHONY : src/Agent.o

# target to build an object file
src/Agent.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Agent.cpp.o
.PHONY : src/Agent.cpp.o

src/Agent.i: src/Agent.cpp.i
.PHONY : src/Agent.i

# target to preprocess a source file
src/Agent.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Agent.cpp.i
.PHONY : src/Agent.cpp.i

src/Agent.s: src/Agent.cpp.s
.PHONY : src/Agent.s

# target to generate assembly for a file
src/Agent.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Agent.cpp.s
.PHONY : src/Agent.cpp.s

src/Area.o: src/Area.cpp.o
.PHONY : src/Area.o

# target to build an object file
src/Area.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Area.cpp.o
.PHONY : src/Area.cpp.o

src/Area.i: src/Area.cpp.i
.PHONY : src/Area.i

# target to preprocess a source file
src/Area.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Area.cpp.i
.PHONY : src/Area.cpp.i

src/Area.s: src/Area.cpp.s
.PHONY : src/Area.s

# target to generate assembly for a file
src/Area.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Area.cpp.s
.PHONY : src/Area.cpp.s

src/CircleArea.o: src/CircleArea.cpp.o
.PHONY : src/CircleArea.o

# target to build an object file
src/CircleArea.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/CircleArea.cpp.o
.PHONY : src/CircleArea.cpp.o

src/CircleArea.i: src/CircleArea.cpp.i
.PHONY : src/CircleArea.i

# target to preprocess a source file
src/CircleArea.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/CircleArea.cpp.i
.PHONY : src/CircleArea.cpp.i

src/CircleArea.s: src/CircleArea.cpp.s
.PHONY : src/CircleArea.s

# target to generate assembly for a file
src/CircleArea.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/CircleArea.cpp.s
.PHONY : src/CircleArea.cpp.s

src/Entity.o: src/Entity.cpp.o
.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i
.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s
.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/Human.o: src/Human.cpp.o
.PHONY : src/Human.o

# target to build an object file
src/Human.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Human.cpp.o
.PHONY : src/Human.cpp.o

src/Human.i: src/Human.cpp.i
.PHONY : src/Human.i

# target to preprocess a source file
src/Human.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Human.cpp.i
.PHONY : src/Human.cpp.i

src/Human.s: src/Human.cpp.s
.PHONY : src/Human.s

# target to generate assembly for a file
src/Human.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Human.cpp.s
.PHONY : src/Human.cpp.s

src/Joint.o: src/Joint.cpp.o
.PHONY : src/Joint.o

# target to build an object file
src/Joint.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Joint.cpp.o
.PHONY : src/Joint.cpp.o

src/Joint.i: src/Joint.cpp.i
.PHONY : src/Joint.i

# target to preprocess a source file
src/Joint.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Joint.cpp.i
.PHONY : src/Joint.cpp.i

src/Joint.s: src/Joint.cpp.s
.PHONY : src/Joint.s

# target to generate assembly for a file
src/Joint.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Joint.cpp.s
.PHONY : src/Joint.cpp.s

src/MovableObject.o: src/MovableObject.cpp.o
.PHONY : src/MovableObject.o

# target to build an object file
src/MovableObject.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/MovableObject.cpp.o
.PHONY : src/MovableObject.cpp.o

src/MovableObject.i: src/MovableObject.cpp.i
.PHONY : src/MovableObject.i

# target to preprocess a source file
src/MovableObject.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/MovableObject.cpp.i
.PHONY : src/MovableObject.cpp.i

src/MovableObject.s: src/MovableObject.cpp.s
.PHONY : src/MovableObject.s

# target to generate assembly for a file
src/MovableObject.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/MovableObject.cpp.s
.PHONY : src/MovableObject.cpp.s

src/Object.o: src/Object.cpp.o
.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i
.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s
.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/RectangleArea.o: src/RectangleArea.cpp.o
.PHONY : src/RectangleArea.o

# target to build an object file
src/RectangleArea.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/RectangleArea.cpp.o
.PHONY : src/RectangleArea.cpp.o

src/RectangleArea.i: src/RectangleArea.cpp.i
.PHONY : src/RectangleArea.i

# target to preprocess a source file
src/RectangleArea.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/RectangleArea.cpp.i
.PHONY : src/RectangleArea.cpp.i

src/RectangleArea.s: src/RectangleArea.cpp.s
.PHONY : src/RectangleArea.s

# target to generate assembly for a file
src/RectangleArea.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/RectangleArea.cpp.s
.PHONY : src/RectangleArea.cpp.s

src/Robot.o: src/Robot.cpp.o
.PHONY : src/Robot.o

# target to build an object file
src/Robot.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Robot.cpp.o
.PHONY : src/Robot.cpp.o

src/Robot.i: src/Robot.cpp.i
.PHONY : src/Robot.i

# target to preprocess a source file
src/Robot.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Robot.cpp.i
.PHONY : src/Robot.cpp.i

src/Robot.s: src/Robot.cpp.s
.PHONY : src/Robot.s

# target to generate assembly for a file
src/Robot.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/Robot.cpp.s
.PHONY : src/Robot.cpp.s

src/StaticObject.o: src/StaticObject.cpp.o
.PHONY : src/StaticObject.o

# target to build an object file
src/StaticObject.cpp.o:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/StaticObject.cpp.o
.PHONY : src/StaticObject.cpp.o

src/StaticObject.i: src/StaticObject.cpp.i
.PHONY : src/StaticObject.i

# target to preprocess a source file
src/StaticObject.cpp.i:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/StaticObject.cpp.i
.PHONY : src/StaticObject.cpp.i

src/StaticObject.s: src/StaticObject.cpp.s
.PHONY : src/StaticObject.s

# target to generate assembly for a file
src/StaticObject.cpp.s:
	$(MAKE) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/src/StaticObject.cpp.s
.PHONY : src/StaticObject.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... toaster"
	@echo "... src/Agent.o"
	@echo "... src/Agent.i"
	@echo "... src/Agent.s"
	@echo "... src/Area.o"
	@echo "... src/Area.i"
	@echo "... src/Area.s"
	@echo "... src/CircleArea.o"
	@echo "... src/CircleArea.i"
	@echo "... src/CircleArea.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/Human.o"
	@echo "... src/Human.i"
	@echo "... src/Human.s"
	@echo "... src/Joint.o"
	@echo "... src/Joint.i"
	@echo "... src/Joint.s"
	@echo "... src/MovableObject.o"
	@echo "... src/MovableObject.i"
	@echo "... src/MovableObject.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/RectangleArea.o"
	@echo "... src/RectangleArea.i"
	@echo "... src/RectangleArea.s"
	@echo "... src/Robot.o"
	@echo "... src/Robot.i"
	@echo "... src/Robot.s"
	@echo "... src/StaticObject.o"
	@echo "... src/StaticObject.i"
	@echo "... src/StaticObject.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

